### ISSUE TITLE
After long reception time scan doesn't resume

### ISSUE THREAD

**Issue by Linden1** [armel/uv-k5-firmware-custom#286] opened 2024-10-27 22:12 UTC
I've never seen this as it actually happens but if I leave my radio scanning a group, if it picks up a signal it'll pause scanning so I can listen. When I come back to the radio later scanning has stopped altogether and the keypad has locked. It seems like if scanning is paused for long enough the scan function fails to resume and the keypad locks after it's preset time (as it automatically should). If I disable the key lock scanning will again fail to restart after long conversations but without the key lock.
This is with the bandscope version of 3.5

**Comment by armel** [comment] 2024-10-27 22:29
First of all, Hi.

What settings do you have in ScanRev (24/67) ?
What settings do you have in KeyLck (30/67) ?

Armel.

**Comment by Linden1** [comment] 2024-10-28 18:41
ScanRev: 10s:000ms
KeyLock: 02m:00s

**Comment by armel** [comment] 2024-10-28 22:06
@Linden1 Ok, I will try to reproduce the problem.

**Comment by Linden1** [comment] 2024-11-02 14:50
@armel I can't reproduce it on another radio with the same settings. I think this radio is either on it's way out or the memory is somehow corrupted. Close this if you want.

**Comment by armel** [comment] 2024-11-02 15:24
@Linden1 Interesting stuff. I tried to reproduce the problem on my side too. But without success. It's strange 🤔

**Comment by armel** [comment] 2024-11-06 15:16
I'm closing this issue because I wasn't able to reproduce it. I will reopen it if new elements can help to reproduce and understand the problem.

**Closed by armel** 2024-11-06 15:16 UTC
